# Generated by Django 2.1.2 on 2018-10-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('idperro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('fechaNac', models.DateField()),
                ('fono', models.IntegerField()),
                ('correo', models.EmailField(max_length=200)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idregion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rescatado',
            fields=[
                ('idRescatado', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('fotografia', models.ImageField(upload_to='')),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('idperro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Perro')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('idtipo_vivienda', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='postulante',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Region'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='tipoVivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TipoVivienda'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='idregion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Region'),
        ),
    ]
