# Generated by Django 2.1.2 on 2018-10-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatado',
            name='fotografia',
            field=models.ImageField(upload_to='static/core/img'),
        ),
    ]
