# Generated by Django 2.1.2 on 2018-10-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181028_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='idciudad',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
