# Generated by Django 2.1.2 on 2018-10-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181028_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatado',
            name='fotografia',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
