# Generated by Django 2.1.2 on 2018-10-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181028_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='tamano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rescatado',
            name='fotografia',
            field=models.ImageField(upload_to=''),
        ),
    ]
